version: "3.9"
services:
  postgres:
    image: postgres:13.3
    container_name: psql
    environment:
      POSTGRES_DB: "meta"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "123"
    volumes:
      - ./start:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"