version: "3.9"
services:
  postgres:
    image: postgres:13.3
    container_name: psql
    environment:
      POSTGRES_DB: "meta"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "123"
    volumes:
      - ./start:/docker-entrypoint-initdb.d
      - ./database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d meta"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G